[package]
name = "file_transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
async_async_io = "0.2"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
